// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {agent} from '../models';
import {mcp} from '../models';

export function CLIProxyAccounts():Promise<Array<backend.CLIProxyAccount>>;

export function CLIProxyLogin(arg1:string,arg2:string):Promise<string>;

export function CLIProxyProviders():Promise<Array<backend.CLIProxyProvider>>;

export function CLIProxySetAccountEnabled(arg1:string,arg2:boolean):Promise<string>;

export function CLIProxySignOut(arg1:string):Promise<string>;

export function CLIProxyStatus():Promise<Record<string, any>>;

export function CLIProxySubmitPrompt(arg1:string):Promise<string>;

export function CancelAllChats():Promise<string>;

export function CancelChat(arg1:string):Promise<string>;

export function CancelScheduledRun(arg1:string):Promise<string>;

export function ChatHistory(arg1:string):Promise<Array<backend.ChatTurn>>;

export function ChatSessions():Promise<Array<backend.ChatSessionInfo>>;

export function DeleteChatSession(arg1:string):Promise<string>;

export function DeleteScheduledPrompt(arg1:string):Promise<string>;

export function Deliverables(arg1:string):Promise<Array<agent.Deliverable>>;

export function EmitAvatarTest(arg1:string):Promise<void>;

export function ExportWorkspaceFile(arg1:string):Promise<string>;

export function GetSettings():Promise<backend.Settings>;

export function GetStatus():Promise<Record<string, any>>;

export function GraphView():Promise<Record<string, any>>;

export function ImportCSV(arg1:string,arg2:string):Promise<string>;

export function ImportFiles(arg1:Array<string>):Promise<Array<string>>;

export function InstallMCPServer(arg1:string,arg2:string,arg3:Array<string>,arg4:Record<string, string>):Promise<string>;

export function InstallSkill(arg1:string,arg2:string):Promise<string>;

export function Life():Promise<backend.LifeData>;

export function MCP():Promise<Array<mcp.ServerStatus>>;

export function MemoryRecall(arg1:string):Promise<string>;

export function MemorySkills():Promise<Array<string>>;

export function OpenInBrowser():Promise<string>;

export function OpenWorkspaceFileExternal(arg1:string):Promise<string>;

export function PendingToolApprovals():Promise<Array<Record<string, any>>>;

export function PickFiles():Promise<Array<string>>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function ReadWorkspaceFileDataURL(arg1:string):Promise<string>;

export function RemoveMCPServer(arg1:string):Promise<string>;

export function RemoveSkill(arg1:string):Promise<string>;

export function ResolveToolApproval(arg1:string,arg2:boolean):Promise<string>;

export function RunScheduledPromptNow(arg1:string):Promise<string>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function ScheduleFromText(arg1:string):Promise<Record<string, any>>;

export function SchedulePrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ScheduledPrompts():Promise<Array<agent.ScheduledPrompt>>;

export function SearchMCPServers(arg1:string):Promise<Record<string, any>>;

export function SearchSkills(arg1:string):Promise<Array<backend.SkillCandidate>>;

export function SendChat(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SetScheduledPromptEnabled(arg1:string,arg2:boolean):Promise<string>;

export function SetUIRules(arg1:string):Promise<string>;

export function Skills():Promise<Array<backend.SkillInfo>>;

export function StartYoloMode(arg1:number):Promise<Record<string, any>>;

export function StopYoloMode():Promise<Record<string, any>>;

export function ToolApprovalInfo(arg1:number):Promise<Record<string, any>>;
