// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Deliverables() {
  return window['go']['main']['App']['Deliverables']();
}

export function EmitAvatarTest(arg1) {
  return window['go']['main']['App']['EmitAvatarTest'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2) {
  return window['go']['main']['App']['SendChat'](arg1, arg2);
}
