// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {agent} from '../models';
import {mcp} from '../models';

export function AddRecord(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<Record<string, any>>;

export function AddSchedule(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Record<string, any>>;

export function CLIProxyAccounts():Promise<Array<backend.CLIProxyAccount>>;

export function CLIProxyLogin(arg1:string,arg2:string):Promise<string>;

export function CLIProxyProviders():Promise<Array<backend.CLIProxyProvider>>;

export function CLIProxySetAccountEnabled(arg1:string,arg2:boolean):Promise<string>;

export function CLIProxySignOut(arg1:string):Promise<string>;

export function CLIProxyStatus():Promise<Record<string, any>>;

export function CLIProxySubmitPrompt(arg1:string):Promise<string>;

export function CancelAllChats():Promise<string>;

export function CancelChat(arg1:string):Promise<string>;

export function CancelScheduledRun(arg1:string):Promise<string>;

export function ChatHistory(arg1:string):Promise<Array<backend.ChatTurn>>;

export function ChatSessions():Promise<Array<backend.ChatSessionInfo>>;

export function Dashboard():Promise<Record<string, any>>;

export function Dashboards():Promise<Array<backend.Dashboard>>;

export function DeleteChatSession(arg1:string):Promise<string>;

export function DeleteDashboard(arg1:string):Promise<Record<string, any>>;

export function DeleteScheduledPrompt(arg1:string):Promise<string>;

export function Deliverables(arg1:string):Promise<Array<agent.Deliverable>>;

export function Doctor():Promise<backend.DoctorReport>;

export function EmitAvatarTest(arg1:string):Promise<void>;

export function ExportWorkspaceFile(arg1:string):Promise<string>;

export function GetSettings():Promise<backend.Settings>;

export function GetStatus():Promise<Record<string, any>>;

export function GraphView():Promise<Record<string, any>>;

export function ImportCSV(arg1:string,arg2:string):Promise<string>;

export function ImportFiles(arg1:Array<string>):Promise<Array<string>>;

export function InstallMCPServer(arg1:string,arg2:string,arg3:Array<string>,arg4:Record<string, string>):Promise<string>;

export function InstallSkill(arg1:string,arg2:string):Promise<string>;

export function Life():Promise<backend.LifeData>;

export function LongRunList():Promise<Array<backend.TaskSummary>>;

export function LongRunStart(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string,arg7:boolean):Promise<string>;

export function LongRunState(arg1:string):Promise<backend.TaskState>;

export function LongRunStop(arg1:string):Promise<boolean>;

export function MCP():Promise<Array<mcp.ServerStatus>>;

export function MemoryRecall(arg1:string):Promise<string>;

export function MemorySkills():Promise<Array<string>>;

export function Notify(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenInBrowser():Promise<string>;

export function OpenWorkspaceFileExternal(arg1:string):Promise<string>;

export function PendingToolApprovals():Promise<Array<Record<string, any>>>;

export function PickFiles():Promise<Array<string>>;

export function PreviewPrompt(arg1:string,arg2:string):Promise<backend.PromptPreview>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function ReadWorkspaceFileDataURL(arg1:string):Promise<string>;

export function RefreshDashboard(arg1:string):Promise<Record<string, any>>;

export function RemoveMCPServer(arg1:string):Promise<string>;

export function RemoveSkill(arg1:string):Promise<string>;

export function RenameDashboard(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ResolveToolApproval(arg1:string,arg2:boolean):Promise<string>;

export function RunScheduledPromptNow(arg1:string):Promise<string>;

export function SaveDashboard(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function ScheduleFromText(arg1:string):Promise<Record<string, any>>;

export function SchedulePrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ScheduledPrompts():Promise<Array<agent.ScheduledPrompt>>;

export function SearchMCPServers(arg1:string):Promise<Record<string, any>>;

export function SearchSkills(arg1:string):Promise<Array<backend.SkillCandidate>>;

export function SendChat(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SetDashboardCron(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetScheduledPromptEnabled(arg1:string,arg2:boolean):Promise<string>;

export function SetUIRules(arg1:string):Promise<string>;

export function SetWindowTheme(arg1:boolean):Promise<void>;

export function Skills():Promise<Array<backend.SkillInfo>>;

export function StartYoloMode(arg1:number):Promise<Record<string, any>>;

export function StopYoloMode():Promise<Record<string, any>>;

export function TestWebhook():Promise<string>;

export function ToolApprovalInfo(arg1:number):Promise<Record<string, any>>;

export function TraceLines(arg1:string,arg2:number):Promise<Array<string>>;
