// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {backend} from '../models';

export function Deliverables():Promise<Array<agent.Deliverable>>;

export function EmitAvatarTest(arg1:string):Promise<void>;

export function GetSettings():Promise<backend.Settings>;

export function GetStatus():Promise<Record<string, any>>;

export function ImportCSV(arg1:string,arg2:string):Promise<string>;

export function Life():Promise<backend.LifeData>;

export function MemoryRecall(arg1:string):Promise<string>;

export function MemorySkills():Promise<Array<string>>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function SendChat(arg1:string,arg2:string):Promise<string>;
