// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Deliverables() {
  return window['go']['main']['App']['Deliverables']();
}

export function EmitAvatarTest(arg1) {
  return window['go']['main']['App']['EmitAvatarTest'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function Life() {
  return window['go']['main']['App']['Life']();
}

export function MCP() {
  return window['go']['main']['App']['MCP']();
}

export function MemoryRecall(arg1) {
  return window['go']['main']['App']['MemoryRecall'](arg1);
}

export function MemorySkills() {
  return window['go']['main']['App']['MemorySkills']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function Skills() {
  return window['go']['main']['App']['Skills']();
}
