// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSchedule'](arg1, arg2, arg3, arg4);
}

export function CLIProxyAccounts() {
  return window['go']['main']['App']['CLIProxyAccounts']();
}

export function CLIProxyLogin(arg1, arg2) {
  return window['go']['main']['App']['CLIProxyLogin'](arg1, arg2);
}

export function CLIProxyProviders() {
  return window['go']['main']['App']['CLIProxyProviders']();
}

export function CLIProxySetAccountEnabled(arg1, arg2) {
  return window['go']['main']['App']['CLIProxySetAccountEnabled'](arg1, arg2);
}

export function CLIProxySignOut(arg1) {
  return window['go']['main']['App']['CLIProxySignOut'](arg1);
}

export function CLIProxyStatus() {
  return window['go']['main']['App']['CLIProxyStatus']();
}

export function CLIProxySubmitPrompt(arg1) {
  return window['go']['main']['App']['CLIProxySubmitPrompt'](arg1);
}

export function CancelAllChats() {
  return window['go']['main']['App']['CancelAllChats']();
}

export function CancelChat(arg1) {
  return window['go']['main']['App']['CancelChat'](arg1);
}

export function CancelScheduledRun(arg1) {
  return window['go']['main']['App']['CancelScheduledRun'](arg1);
}

export function ChatHistory(arg1) {
  return window['go']['main']['App']['ChatHistory'](arg1);
}

export function ChatSessions() {
  return window['go']['main']['App']['ChatSessions']();
}

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DeleteScheduledPrompt(arg1) {
  return window['go']['main']['App']['DeleteScheduledPrompt'](arg1);
}

export function Deliverables(arg1) {
  return window['go']['main']['App']['Deliverables'](arg1);
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function EmitAvatarTest(arg1) {
  return window['go']['main']['App']['EmitAvatarTest'](arg1);
}

export function ExportWorkspaceFile(arg1) {
  return window['go']['main']['App']['ExportWorkspaceFile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GraphView() {
  return window['go']['main']['App']['GraphView']();
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function InstallMCPServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallMCPServer'](arg1, arg2, arg3, arg4);
}

export function InstallSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2);
}

export function Life() {
  return window['go']['main']['App']['Life']();
}

export function LongRunList() {
  return window['go']['main']['App']['LongRunList']();
}

export function LongRunStart(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LongRunStart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LongRunState(arg1) {
  return window['go']['main']['App']['LongRunState'](arg1);
}

export function LongRunStop(arg1) {
  return window['go']['main']['App']['LongRunStop'](arg1);
}

export function MCP() {
  return window['go']['main']['App']['MCP']();
}

export function MemoryRecall(arg1) {
  return window['go']['main']['App']['MemoryRecall'](arg1);
}

export function MemorySkills() {
  return window['go']['main']['App']['MemorySkills']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function OpenWorkspaceFileExternal(arg1) {
  return window['go']['main']['App']['OpenWorkspaceFileExternal'](arg1);
}

export function PendingToolApprovals() {
  return window['go']['main']['App']['PendingToolApprovals']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PreviewPrompt(arg1, arg2) {
  return window['go']['main']['App']['PreviewPrompt'](arg1, arg2);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function ReadWorkspaceFileDataURL(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFileDataURL'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveSkill(arg1) {
  return window['go']['main']['App']['RemoveSkill'](arg1);
}

export function ResolveToolApproval(arg1, arg2) {
  return window['go']['main']['App']['ResolveToolApproval'](arg1, arg2);
}

export function RunScheduledPromptNow(arg1) {
  return window['go']['main']['App']['RunScheduledPromptNow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScheduleFromText(arg1) {
  return window['go']['main']['App']['ScheduleFromText'](arg1);
}

export function SchedulePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SchedulePrompt'](arg1, arg2, arg3, arg4);
}

export function ScheduledPrompts() {
  return window['go']['main']['App']['ScheduledPrompts']();
}

export function SearchMCPServers(arg1) {
  return window['go']['main']['App']['SearchMCPServers'](arg1);
}

export function SearchSkills(arg1) {
  return window['go']['main']['App']['SearchSkills'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function SetScheduledPromptEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetScheduledPromptEnabled'](arg1, arg2);
}

export function SetUIRules(arg1) {
  return window['go']['main']['App']['SetUIRules'](arg1);
}

export function SetWindowTheme(arg1) {
  return window['go']['main']['App']['SetWindowTheme'](arg1);
}

export function Skills() {
  return window['go']['main']['App']['Skills']();
}

export function StartYoloMode(arg1) {
  return window['go']['main']['App']['StartYoloMode'](arg1);
}

export function StopYoloMode() {
  return window['go']['main']['App']['StopYoloMode']();
}

export function ToolApprovalInfo(arg1) {
  return window['go']['main']['App']['ToolApprovalInfo'](arg1);
}
